title: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/alfonsograna" # the subpath of your site, e.g. /blog
url: "https://agrana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Social media profiles
medium_username: yourusername
linkedin_username: yourusername

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Theme configuration
show_downloads: false
show_excerpts: true

# Cross-posting settings
canonical_url: true
medium_crosspost: true

# Allow future posts to be displayed
future: true
