title: "Alfonso Grana"
email: a@alfonsograna.com
description: "Build ship repeat."
baseurl: "" # served from the root of the custom domain
url: "https://alfonsograna.com"
twitter_username: "agrana"
github_username:  "agrana"
repository_url: "https://github.com/agrana/alfonsograna"
github:
  repository_url: "https://github.com/agrana/alfonsograna"

# Author information
author: "Alfonso Grana"
author_name: "Alfonso Grana"

# Social media profiles
medium_username: alfonso.grana
linkedin_username: alfonsograna

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Theme configuration
show_downloads: false
show_excerpts: true

# Cross-posting settings
canonical_url: true
medium_crosspost: true

# Public site identifier for Cloudflare Web Analytics
cloudflare_web_analytics_token: "b9f535ff33364995a4ec4eaa3636be26"

# Allow future posts to be displayed
future: true
