title: "Alfonso's Blog"
email: a@alfonsograna.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/alfonsograna" # the subpath of your site, e.g. /blog
url: "https://agrana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "agrana"
github_username:  "agrana"

# Author information
author: "Alfonso Grana"
author_name: "Alfonso Grana"

# Social media profiles
medium_username: alfonso.grana
linkedin_username: alfonsograna

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-mermaid

# Theme configuration
show_downloads: false
show_excerpts: true

# Cross-posting settings
canonical_url: true
medium_crosspost: true

# Allow future posts to be displayed
future: true

# Mermaid configuration
mermaid:
  version: "10.6.1"
  theme: "dark"
  config:
    theme: "dark"
    themeVariables:
      primaryColor: "#00ff00"
      primaryTextColor: "#ffffff"
      primaryBorderColor: "#00ff00"
      lineColor: "#00ff00"
      secondaryColor: "#006100"
      tertiaryColor: "#ffffff"
